version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/BlobAssets"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Common"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/CustomerStories"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/DotnetFrameworkReleases"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/EBooks"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/LearnContent"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Uploader.DotnetCoreReleases"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Uploader.Resources"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
